version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      - run:
          name: Show current branch (test)
          command: echo ${CIRCLE_BRANCH}
      # https://medium.freecodecamp.org/our-journey-for-using-circleci-2-0-to-build-and-deploy-an-angular-app-to-aws-s3-8e7ea3f51503
      # Restore local dependencies from cache
      # todo implement the fancy hashing script mentioned in the link above
      - restore_cache:
                      key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
                      key: dependency-cache-{{ checksum "package.json" }}
                      paths:
                        - node_modules
      # Run tests
      - run: npm run test
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Show current branch (build)
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                  - node_modules
      - run:
          name: Build Angular Project to dist/
          command: npm run build --prod
  deploy-job:
     docker:
       - image: my-image-version-tag
     working_directory: ~/project
     steps:
     # Log the current branch
       - run:
           name: Show current branch
           command: echo ${CIRCLE_BRANCH}
       # Restore cache from the build job which contains the
       # dist folder that needs to be deployed
       - restore_cache:
           key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
       - run:
           name: Deploy Master to Firebase or Other Branch to Staging

           command:
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    echo 'deploying to prod';
                    ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
                else
                    echo 'deploying to staging';
                    ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN -p staging
                fi


deploy:
  jobs:
    - test
    - build
    - deploy-job:
        requires:
          - test
          - build
pro-only: true
